name: Lint

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
        with:
          args: ". --diff --check"
      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1
      - name: flake8
        run: |
          pip install flake8
          flake8 pymysql
